runtime: python39

handlers:
  - url: /css
    static_dir: css

  - url: /images
    static_dir: images

  - url: /javascripts
    static_dir: javascripts

  - url: /resume
    static_dir: resume

  - url: /(.*\.html)
    static_files: \1
    upload: (.*\.html)

  - url: /
    static_files: index.html
    upload: index.html
